//! # ui_lower.rs — Build-Time UiDef → DrawCmd Lowering Pass
//!
//! Converts parsed `UiDef` AST nodes into static `DrawCmd` slices.
//! Output is a `Vec<DrawCmd>` intended for embedding into `.rodata`
//! via `include_bytes!` or `const` initialization at build time.
//!
//! All math is integer-only (MilliUnit + Permyriad). Zero allocations
//! at runtime — the lowered commands are baked into the binary.

use crate::vixel::UiDef;
use crate::vixel::ColorValue;

/// Magenta sentinel emitted when a `ColorValue::TokenRef` has no resolved binding.
/// Pure magenta (not in the Synthesia palette) intentionally stands out in debug
/// renders, making unresolved tokens visually obvious.
const UNRESOLVED_TOKEN_SENTINEL: u32 = 0xFF00FFFF;

/// A named static DrawCmd slice, ready for .rodata embedding.
#[derive(Debug, Clone)]
pub struct LoweredUiPanel {
    /// The panel's `const` name, as emitted into the generated Rust source.
    pub name: String,
}

/// Pack `material_idx` and `vibe_mask` into a u32 for `QuadInstance.packed_flags`.
///
/// Layout: bits [0..7] = material_idx, bits [8..15] = vibe_mask.
/// Matches the WGSL unpacking in the uber-shader fragment stage.
pub const fn pack_flags(material_idx: u8, vibe_mask: u8) -> u32 {
    (material_idx as u32) | ((vibe_mask as u32) << 8)
}

/// Generate a Rust source fragment containing `const` DrawCmd arrays.
///
/// Output is valid Rust that can be written to a generated `.rs` file
/// and included via `include!()` in the build target.
///
/// Example output:
/// ```ignore
/// pub const HEALTH_BAR: [StaticUiCmd; 1] = [
///     StaticUiCmd { x: 10000, y: 5000, w: 200000, h: 12000, color: 0x50A060FF, radius: 4, packed_flags: 0x0101 },
/// ];
/// ```
pub fn codegen_static_ui(defs: &[UiDef]) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by forge-ast ui_lower. Do not edit.\n\n");
    out.push_str("#[derive(Copy, Clone, Debug)]\n");
    out.push_str("#[repr(C)]\n");
    out.push_str("pub struct StaticUiCmd {\n");
    out.push_str("    pub x: i64,\n");
    out.push_str("    pub y: i64,\n");
    out.push_str("    pub w: i64,\n");
    out.push_str("    pub h: i64,\n");
    out.push_str("    pub color: u32,\n");
    out.push_str("    pub radius: u16,\n");
    out.push_str("    pub packed_flags: u32,\n");
    out.push_str("}\n\n");

    for ui in defs {
        let name = ui.name_str().to_uppercase().replace(' ', "_");
        let flags = pack_flags(ui.material_idx, ui.vibe_mask);
        let color_val = match &ui.color {
            ColorValue::Literal(v) => *v,
            ColorValue::TokenRef(_) => UNRESOLVED_TOKEN_SENTINEL,
        };
        out.push_str(&format!(
            "pub const {name}: [StaticUiCmd; 1] = [\n    StaticUiCmd {{ x: {}, y: {}, w: {}, h: {}, color: 0x{:08X}, radius: {}, packed_flags: 0x{:04X} }},\n];\n\n",
            ui.x, ui.y, ui.w, ui.h, color_val, ui.radius, flags,
        ));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_ui(name: &str, x: i64, y: i64, w: i64, h: i64, mat: u8, vibe: u8) -> UiDef {
        let mut ui = UiDef::default();
        let bytes = name.as_bytes();
        let len = bytes.len().min(32);
        ui.name[..len].copy_from_slice(&bytes[..len]);
        ui.name_len = len;
        ui.x = x;
        ui.y = y;
        ui.w = w;
        ui.h = h;
        ui.color = ColorValue::Literal(0x50A060FF);
        ui.material_idx = mat;
        ui.vibe_mask = vibe;
        ui.radius = 4;
        ui
    }

    #[test]
    fn pack_flags_layout() {
        assert_eq!(pack_flags(1, 0x03), 0x0301);
        assert_eq!(pack_flags(0, 0), 0);
        assert_eq!(pack_flags(3, 0x0F), 0x0F03);
    }

    #[test]
    fn codegen_produces_valid_const() {
        let defs = vec![make_ui("panel", 10000, 5000, 500000, 300000, 1, 0x01)];
        let code = codegen_static_ui(&defs);
        assert!(code.contains("pub const PANEL:"));
        assert!(code.contains("x: 10000"));
        assert!(code.contains("packed_flags: 0x0101"));
        assert!(code.contains("StaticUiCmd"));
    }
}
