//! Twelve hand-authored First Lock specs.
#![allow(dead_code)]
use crate::lore_core::*; use crate::lore_registry::*;
const ALL:&[Era]=&[Era::Ancient,Era::Golden,Era::Decay,Era::Void]; const GDV:&[Era]=&[Era::Golden,Era::Decay,Era::Void]; const ADV:&[Era]=&[Era::Ancient,Era::Decay,Era::Void];
pub const FIRST_LOCKS:[FirstLockDef;12]=[
FirstLockDef{id:FirstLockId(0),slug:"red_debt_first_strike_not_taken",account:HiddenAccount::RedDebt,zone:ZoneHash(0x1001),required_eras:ADV,demand_a:MechanicalDemand::Aggression,demand_b:MechanicalDemand::Patience,final_action:FirstLockFinalAction::DoNotRingBell,world_first_relic:RelicId(1),echo_relic:RelicId(1001),puzzle_scar:PuzzleScarId(1),public_ledger_line:"The first strike was found and left unused."},
FirstLockDef{id:FirstLockId(1),slug:"stone_root_weight_carried_across_void",account:HiddenAccount::StoneRoot,zone:ZoneHash(0x1002),required_eras:ALL,demand_a:MechanicalDemand::StationaryChannel,demand_b:MechanicalDemand::Mobility,final_action:FirstLockFinalAction::Bury,world_first_relic:RelicId(2),echo_relic:RelicId(1002),puzzle_scar:PuzzleScarId(2),public_ledger_line:"The impossible weight was carried until it became ground."},
FirstLockDef{id:FirstLockId(2),slug:"double_witness_contradiction_preserved",account:HiddenAccount::DoubleWitness,zone:ZoneHash(0x1003),required_eras:GDV,demand_a:MechanicalDemand::Diplomacy,demand_b:MechanicalDemand::Theft,final_action:FirstLockFinalAction::SpeakName,world_first_relic:RelicId(3),echo_relic:RelicId(1003),puzzle_scar:PuzzleScarId(3),public_ledger_line:"Two witnesses disagreed and both survived the page."},
FirstLockDef{id:FirstLockId(3),slug:"grave_water_name_kept_wet",account:HiddenAccount::GraveWater,zone:ZoneHash(0x1004),required_eras:ALL,demand_a:MechanicalDemand::DeathRoute,demand_b:MechanicalDemand::WitnessBuilding,final_action:FirstLockFinalAction::DieInPlace,world_first_relic:RelicId(4),echo_relic:RelicId(1004),puzzle_scar:PuzzleScarId(4),public_ledger_line:"A name was kept wet enough to return."},
FirstLockDef{id:FirstLockId(4),slug:"crownless_roar_command_refused",account:HiddenAccount::CrownlessRoar,zone:ZoneHash(0x1005),required_eras:GDV,demand_a:MechanicalDemand::Aggression,demand_b:MechanicalDemand::Diplomacy,final_action:FirstLockFinalAction::Refuse,world_first_relic:RelicId(5),echo_relic:RelicId(1005),puzzle_scar:PuzzleScarId(5),public_ledger_line:"Command gathered around a head that would not take the crown."},
FirstLockDef{id:FirstLockId(5),slug:"clean_index_record_corrected_without_erasure",account:HiddenAccount::CleanIndex,zone:ZoneHash(0x1006),required_eras:ALL,demand_a:MechanicalDemand::InventoryPrecision,demand_b:MechanicalDemand::Patience,final_action:FirstLockFinalAction::Craft,world_first_relic:RelicId(6),echo_relic:RelicId(1006),puzzle_scar:PuzzleScarId(6),public_ledger_line:"The record was corrected without becoming clean of warmth."},
FirstLockDef{id:FirstLockId(6),slug:"equal_knife_harm_balanced_without_revenge",account:HiddenAccount::EqualKnife,zone:ZoneHash(0x1007),required_eras:ADV,demand_a:MechanicalDemand::ParryTiming,demand_b:MechanicalDemand::Diplomacy,final_action:FirstLockFinalAction::Spare,world_first_relic:RelicId(7),echo_relic:RelicId(1007),puzzle_scar:PuzzleScarId(7),public_ledger_line:"The wound was measured until revenge ran out."},
FirstLockDef{id:FirstLockId(7),slug:"venom_wedding_oath_poison_not_cured",account:HiddenAccount::VenomWedding,zone:ZoneHash(0x1008),required_eras:GDV,demand_a:MechanicalDemand::Theft,demand_b:MechanicalDemand::WitnessBuilding,final_action:FirstLockFinalAction::StaySilent,world_first_relic:RelicId(8),echo_relic:RelicId(1008),puzzle_scar:PuzzleScarId(8),public_ledger_line:"An oath tasted of poison and was not cured."},
FirstLockDef{id:FirstLockId(8),slug:"far_wound_route_outside_known_map",account:HiddenAccount::FarWound,zone:ZoneHash(0x1009),required_eras:ALL,demand_a:MechanicalDemand::Mobility,demand_b:MechanicalDemand::Crafting,final_action:FirstLockFinalAction::WalkAway,world_first_relic:RelicId(9),echo_relic:RelicId(1009),puzzle_scar:PuzzleScarId(9),public_ledger_line:"The road opened outward and did not ask to be named."},
FirstLockDef{id:FirstLockId(9),slug:"last_toll_bell_not_rung",account:HiddenAccount::LastToll,zone:ZoneHash(0x1010),required_eras:ALL,demand_a:MechanicalDemand::StationaryChannel,demand_b:MechanicalDemand::Theft,final_action:FirstLockFinalAction::DoNotRingBell,world_first_relic:RelicId(10),echo_relic:RelicId(1010),puzzle_scar:PuzzleScarId(10),public_ledger_line:"The bell that proved the debt was buried under the road."},
FirstLockDef{id:FirstLockId(10),slug:"hollow_star_map_body_soul_unstitched",account:HiddenAccount::HollowStar,zone:ZoneHash(0x1011),required_eras:ALL,demand_a:MechanicalDemand::Theft,demand_b:MechanicalDemand::InventoryPrecision,final_action:FirstLockFinalAction::LoseOnPurpose,world_first_relic:RelicId(11),echo_relic:RelicId(1011),puzzle_scar:PuzzleScarId(11),public_ledger_line:"The map stopped believing the body."},
FirstLockDef{id:FirstLockId(11),slug:"mercy_drowned_debt_dissolved_unrescued",account:HiddenAccount::MercyDrowned,zone:ZoneHash(0x1012),required_eras:ADV,demand_a:MechanicalDemand::Patience,demand_b:MechanicalDemand::Refusal,final_action:FirstLockFinalAction::Spare,world_first_relic:RelicId(12),echo_relic:RelicId(1012),puzzle_scar:PuzzleScarId(12),public_ledger_line:"The debt softened under water and no one was rescued from mercy."},
];
