//! Integer harmonic/alchemical physics.
#![allow(dead_code)]
use crate::lore_core::Permyriad;
#[derive(Debug,Clone,Copy,PartialEq,Eq,Hash)] pub enum Element{Fire,Air,Water,Earth}
#[derive(Debug,Clone,Copy,PartialEq,Eq,Hash)] pub enum AlchemicalTier{Nigredo,Albedo,Citrinitas,Rubedo,AspirationalMatter}
#[derive(Debug,Clone,Copy)] pub struct HarmonicBody{pub element:Element,pub tier:AlchemicalTier,pub resonance_hz:i32,pub inverse_hz:bool,pub mass_q:Permyriad,pub volatility_q:Permyriad,pub cohesion_q:Permyriad,pub shockwave_q:Permyriad,pub suction_q:Permyriad}
pub const NIGREDO_HZ:i32=40; pub const ALBEDO_HZ:i32=432; pub const CITRINITAS_INVERSE_HZ:i32=408; pub const RUBEDO_HZ:i32=800; pub const PHASE_CANCEL_SUM_HZ:i32=840; pub const PHYSICS_HZ:i32=120;
pub fn default_body(element:Element,tier:AlchemicalTier)->HarmonicBody{match tier{AlchemicalTier::Nigredo=>HarmonicBody{element,tier,resonance_hz:NIGREDO_HZ,inverse_hz:false,mass_q:30000,volatility_q:1000,cohesion_q:9000,shockwave_q:0,suction_q:0},AlchemicalTier::Albedo=>HarmonicBody{element,tier,resonance_hz:ALBEDO_HZ,inverse_hz:false,mass_q:10000,volatility_q:2500,cohesion_q:10000,shockwave_q:2500,suction_q:0},AlchemicalTier::Citrinitas=>HarmonicBody{element,tier,resonance_hz:CITRINITAS_INVERSE_HZ,inverse_hz:true,mass_q:5000,volatility_q:7500,cohesion_q:4000,shockwave_q:1000,suction_q:8000},AlchemicalTier::Rubedo=>HarmonicBody{element,tier,resonance_hz:RUBEDO_HZ,inverse_hz:false,mass_q:2500,volatility_q:12000,cohesion_q:1000,shockwave_q:10000,suction_q:0},AlchemicalTier::AspirationalMatter=>HarmonicBody{element,tier,resonance_hz:963,inverse_hz:false,mass_q:50000,volatility_q:20000,cohesion_q:20000,shockwave_q:20000,suction_q:20000}}}
#[derive(Debug,Clone,Copy,PartialEq,Eq)] pub enum HarmonicCollisionOutcome{Stable,HeavyDrag,RadialRepel,InverseSuction,PlasmaShockwave,PhaseCancellation,SingularityWarp}
pub fn phase_cancels(a:HarmonicBody,b:HarmonicBody)->bool{a.resonance_hz+b.resonance_hz==PHASE_CANCEL_SUM_HZ||(a.inverse_hz&&(a.resonance_hz+b.resonance_hz-PHASE_CANCEL_SUM_HZ).abs()<=2)||(b.inverse_hz&&(a.resonance_hz+b.resonance_hz-PHASE_CANCEL_SUM_HZ).abs()<=2)}
pub fn resolve_harmonic_collision(a:HarmonicBody,b:HarmonicBody)->HarmonicCollisionOutcome{if phase_cancels(a,b){return HarmonicCollisionOutcome::PhaseCancellation} if matches!(a.tier,AlchemicalTier::AspirationalMatter)|matches!(b.tier,AlchemicalTier::AspirationalMatter){return HarmonicCollisionOutcome::SingularityWarp} if a.shockwave_q>=8000||b.shockwave_q>=8000{return HarmonicCollisionOutcome::PlasmaShockwave} if a.suction_q>=5000||b.suction_q>=5000{return HarmonicCollisionOutcome::InverseSuction} if a.mass_q>=25000||b.mass_q>=25000{return HarmonicCollisionOutcome::HeavyDrag} if a.cohesion_q>=9000&&b.cohesion_q>=9000{return HarmonicCollisionOutcome::RadialRepel} HarmonicCollisionOutcome::Stable}
pub fn mass_scaled_velocity_mm_per_s(v:i64,body:HarmonicBody)->i64{v.saturating_mul(10000).saturating_div(body.mass_q.max(1) as i64)} pub fn shockwave_radius_mm(body:HarmonicBody,base:i64)->i64{base.saturating_mul((10000+body.shockwave_q).max(0) as i64).saturating_div(10000)} pub fn suction_velocity_mm_per_s(body:HarmonicBody,base:i64)->i64{-base.saturating_mul(body.suction_q.max(0) as i64).saturating_div(10000)}
