//! AUTO-GENERATED by `cargo xtask gen-verbs` — do not hand-edit.
//! Source: `src/verbs/*.ron` + `src/verbs/ORDER.tsv`. Re-run the
//! generator after editing either; a stale file here is a defect.

/// Extension table — ids continue from the legacy `wire::TOOL_TABLE`.
pub const EXT_TOOL_TABLE: &[&str] = &[
    "lsp_hover",
    "example_empty",
    "example_keyed",
    "example_verbatim",
];

/// First id in the generated range (legacy table has 54 entries).
pub const EXT_ID_BASE: u16 = 55;

#[derive(Debug, Clone, PartialEq)]
#[allow(missing_docs)]
pub enum GeneratedMsg {
    LspHover { line: u32, character: u32, source: String },
    ExampleEmpty,
    ExampleKeyed { label: String },
    ExampleVerbatim { source: String },
}

impl GeneratedMsg {
    /// Encode to wire text via the shared `codegen::encode_*` helpers.
    pub fn encode(&self) -> String {
        match self {
            GeneratedMsg::LspHover { line, character, source } => crate::codegen::encode_keyed_tail(&[("line", line.to_string()), ("character", character.to_string())], source),
            GeneratedMsg::ExampleEmpty => String::new(),
            GeneratedMsg::ExampleKeyed { label } => crate::codegen::encode_keyed(&[("label", label.to_string())]),
            GeneratedMsg::ExampleVerbatim { source } => crate::codegen::encode_verbatim(source),
        }
    }

    /// Decode by op name via the shared `codegen::decode_*` helpers.
    pub fn decode(op: &str, text: &str) -> Option<Self> {
        match op {
            "lsp_hover" => {
                let (v, tail) = crate::codegen::decode_keyed_tail(text, &["line", "character"]);
                Some(GeneratedMsg::LspHover { line: v[0].parse().unwrap_or(0), character: v[1].parse().unwrap_or(0),  source: tail })
            }
            "example_empty" => Some(GeneratedMsg::ExampleEmpty),
            "example_keyed" => {
                let v = crate::codegen::decode_keyed(text, &["label"]);
                Some(GeneratedMsg::ExampleKeyed { label: v[0].clone(),  })
            }
            "example_verbatim" => Some(GeneratedMsg::ExampleVerbatim { source: crate::codegen::decode_verbatim(text) }),
            _ => None,
        }
    }
}
