//! Prairie Start dialogue engine — DEFERRED to nde_chat.rs + forge-book.
//!
//! The prairie_start_dialogue() is authored in forge-book-v3::dialogue (L05 one-home law).
//! NPC responses are generated by Gemma 9B sidecar via nde_chat wiring.
//! This stub is a landing place for future dialogue state/history if needed.
