// Copyright (c) 2026 Sean Morin, Edmonton River Valley, Alberta. All rights reserved.
// SPDX-License-Identifier: MIT

//! Somatic Star Codebook — Offline Zero-Heap View over Baked HYG Star Catalog.
//!
//! Drains the binary `hyg_baked.bin` generated by `xtask/src/hyg_bake.rs` and provides
//! $O(1)$ zero-copy star centroid parsing, $L_2$ Euclidean nearest-neighbor search, and
//! continuous 5D somatic detokenization without dynamic heap allocations.

/// Magic bytes at the start of a baked HYG catalog: `"HYGC"`.
pub const HYG_MAGIC: [u8; 4] = *b"HYGC";
/// Binary format version.
pub const HYG_VERSION: u32 = 1;
/// Header size in bytes: magic(4) + version(4) + star_count(4) + anomaly_count(4).
pub const HEADER_LEN: usize = 16;
/// Teff LUT size in bytes: 256 entries * 4 bytes RGBA.
pub const TEFF_LUT_LEN: usize = 256 * 4;
/// Bytes per on-disk star record. Restated from `xtask/src/hyg_bake.rs::BYTES_PER_STAR`.
pub const BYTES_PER_STAR: usize = 17;
/// Bytes per sparse anomaly record: star_idx(4) + Pexil(8).
pub const BYTES_PER_ANOMALY: usize = 12;

/// `0xFF` in `lore_idx` means "no lore join" — matches `xtask/src/hyg_bake.rs::NO_LORE`.
pub const NO_LORE: u8 = 0xFF;

/// One baked star centroid: pure integers decoded directly from the binary asset.
#[repr(C, align(16))]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct BakedStarCentroid {
    /// Catalogue index within the baked star table ($0 \dots N-1$).
    pub star_idx: u32,
    /// Right ascension, $0 \dots 2^{32}-1$ mapping to $0.00^\circ \dots 360.00^\circ$.
    pub ra_u32: u32,
    /// Declination, $-2^{31} \dots 2^{31}-1$ mapping to $-90.00^\circ \dots +90.00^\circ$.
    pub dec_i32: i32,
    /// Apparent magnitude in Permyriad ($\text{mag} \times 10{,}000$; negative = brighter).
    pub mag_permyriad: i32,
    /// Distance in parsecs, clamped to u16 range ($0$ = unknown).
    pub distance_u16: u16,
    /// Index into the Teff RGBA LUT (blackbody colour).
    pub teff_idx: u8,
    /// Criticality/saliency tier: 0 (brightest) .. 4 (not rendered).
    pub lode_tier: u8,
    /// Index into `sky_data::CATALOG` (the 13moons lore catalog), or [`NO_LORE`].
    pub lore_idx: u8,
}

impl BakedStarCentroid {
    /// Normalize Right Ascension to $[0.0, 1.0]$.
    #[inline(always)]
    pub fn ra_normalized(&self) -> f32 {
        (self.ra_u32 as f64 / 4294967295.0) as f32
    }

    /// Normalize Declination to $[-1.0, 1.0]$.
    #[inline(always)]
    pub fn dec_normalized(&self) -> f32 {
        (self.dec_i32 as f64 / 2147483647.0) as f32
    }

    /// Normalize Apparent Magnitude to $[0.0, 1.0]$ across range $[-2.00, +15.00]$.
    #[inline(always)]
    pub fn mag_normalized(&self) -> f32 {
        let mag_f = self.mag_permyriad as f32 / 10000.0;
        ((mag_f + 2.0) / 17.0).clamp(0.0, 1.0)
    }

    /// Compute deterministic stellar resonant pulsation frequency in milli-Hz ($0 \dots 100{,}000\text{ mHz}$).
    #[inline(always)]
    pub fn resonant_milli_hz(&self) -> u32 {
        let base_hz = 7830u32; // Fundamental Schumann base: 7.83 Hz = 7830 mHz
        let teff_mod = (self.teff_idx as u32) * 150;
        let dist_mod = (self.distance_u16 as u32) % 20000;
        (base_hz + teff_mod + dist_mod).min(100_000)
    }
}

/// Zero-copy memory-mapped or static slice view over `hyg_baked.bin`.
pub struct StarCodebookView<'a> {
    raw_bytes: &'a [u8],
    star_count: usize,
    anomaly_count: usize,
    stars_offset: usize,
}

impl<'a> StarCodebookView<'a> {
    /// Parse and validate a baked HYG catalog header from a byte slice.
    pub fn parse(bytes: &'a [u8]) -> Result<Self, &'static str> {
        if bytes.len() < HEADER_LEN + TEFF_LUT_LEN {
            return Err("HYG catalog buffer too short for header and LUT");
        }
        if bytes[0..4] != HYG_MAGIC {
            return Err("HYG catalog magic mismatch");
        }
        let star_count = u32::from_le_bytes([bytes[8], bytes[9], bytes[10], bytes[11]]) as usize;
        let anomaly_count = u32::from_le_bytes([bytes[12], bytes[13], bytes[14], bytes[15]]) as usize;

        let stars_offset = HEADER_LEN + TEFF_LUT_LEN;
        let required_len = stars_offset + (star_count * BYTES_PER_STAR) + (anomaly_count * BYTES_PER_ANOMALY);

        if bytes.len() < required_len {
            return Err("HYG catalog truncated: star/anomaly payload incomplete");
        }

        Ok(Self {
            raw_bytes: bytes,
            star_count,
            anomaly_count,
            stars_offset,
        })
    }

    /// Total count of baked stars in the codebook.
    #[inline(always)]
    pub fn star_count(&self) -> usize {
        self.star_count
    }

    /// Total count of sparse anomalies in the codebook.
    #[inline(always)]
    pub fn anomaly_count(&self) -> usize {
        self.anomaly_count
    }

    /// Retrieve the $i$-th baked star centroid in $O(1)$ zero heap allocations.
    #[inline(always)]
    pub fn get_star(&self, idx: usize) -> Option<BakedStarCentroid> {
        if idx >= self.star_count {
            return None;
        }
        let off = self.stars_offset + (idx * BYTES_PER_STAR);
        let b = &self.raw_bytes[off..off + BYTES_PER_STAR];

        let ra_u32 = u32::from_le_bytes([b[0], b[1], b[2], b[3]]);
        let dec_i32 = i32::from_le_bytes([b[4], b[5], b[6], b[7]]);
        let mag_permyriad = i32::from_le_bytes([b[8], b[9], b[10], b[11]]);
        let distance_u16 = u16::from_le_bytes([b[12], b[13]]);
        let teff_idx = b[14];
        let lode_tier = b[15];
        let lore_idx = b[16];

        Some(BakedStarCentroid {
            star_idx: idx as u32,
            ra_u32,
            dec_i32,
            mag_permyriad,
            distance_u16,
            teff_idx,
            lode_tier,
            lore_idx,
        })
    }

    /// Find the nearest star centroid within a specified saliency tier limit ($L_2$ Euclidean distance).
    ///
    /// - `query_ra_norm`: Target normalized RA in $[0.0, 1.0]$.
    /// - `query_dec_norm`: Target normalized Dec in $[-1.0, 1.0]$.
    /// - `query_mag_norm`: Target normalized magnitude in $[0.0, 1.0]$.
    /// - `max_tier`: Maximum lode tier to consider ($0 \dots 4$, where $0$ = brightest).
    pub fn nearest_centroid_l2(
        &self,
        query_ra_norm: f32,
        query_dec_norm: f32,
        query_mag_norm: f32,
        max_tier: u8,
    ) -> Option<(usize, BakedStarCentroid, f32)> {
        let mut best_idx = None;
        let mut best_star = None;
        let mut best_dist_sq = f32::MAX;

        for i in 0..self.star_count {
            if let Some(star) = self.get_star(i) {
                if star.lode_tier > max_tier {
                    continue;
                }
                let d_ra = star.ra_normalized() - query_ra_norm;
                let d_dec = star.dec_normalized() - query_dec_norm;
                let d_mag = star.mag_normalized() - query_mag_norm;

                let dist_sq = d_ra * d_ra + d_dec * d_dec + d_mag * d_mag;
                if dist_sq < best_dist_sq {
                    best_dist_sq = dist_sq;
                    best_idx = Some(i);
                    best_star = Some(star);
                }
            }
        }

        match (best_idx, best_star) {
            (Some(idx), Some(star)) => Some((idx, star, best_dist_sq)),
            _ => None,
        }
    }

    /// Detokenizes a continuous 5D somatic coordinate embedding `[ra, dec, mag, spectral, hz]`
    /// directly into the nearest star centroid in the codebook.
    #[inline(always)]
    pub fn detokenize_embedding(&self, coords_5d: &[f32; 5]) -> Option<BakedStarCentroid> {
        let ra_norm = coords_5d[0];
        let dec_norm = coords_5d[1];
        let mag_norm = coords_5d[2];

        self.nearest_centroid_l2(ra_norm, dec_norm, mag_norm, 4)
            .map(|(_, star, _)| star)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_codebook_header_parsing_and_lookup() {
        let mut test_bytes = [0u8; HEADER_LEN + TEFF_LUT_LEN + (BYTES_PER_STAR * 2)];
        // Magic HYGC
        test_bytes[0..4].copy_from_slice(&HYG_MAGIC);
        // Version 1
        test_bytes[4..8].copy_from_slice(&1u32.to_le_bytes());
        // Star count 2
        test_bytes[8..12].copy_from_slice(&2u32.to_le_bytes());
        // Anomaly count 0
        test_bytes[12..16].copy_from_slice(&0u32.to_le_bytes());

        // Star 0 (Sirius-like: RA=10128, Dec=-1671, Mag=-14600, dist=26, teff=128, tier=0, lore=0)
        let off0 = HEADER_LEN + TEFF_LUT_LEN;
        test_bytes[off0..off0 + 4].copy_from_slice(&10128000u32.to_le_bytes());
        test_bytes[off0 + 4..off0 + 8].copy_from_slice(&(-1671000i32).to_le_bytes());
        test_bytes[off0 + 8..off0 + 12].copy_from_slice(&(-14600i32).to_le_bytes());
        test_bytes[off0 + 12..off0 + 14].copy_from_slice(&26u16.to_le_bytes());
        test_bytes[off0 + 14] = 128;
        test_bytes[off0 + 15] = 0;
        test_bytes[off0 + 16] = 0;

        // Star 1 (Polaris-like)
        let off1 = off0 + BYTES_PER_STAR;
        test_bytes[off1..off1 + 4].copy_from_slice(&4294967295u32.to_le_bytes());
        test_bytes[off1 + 4..off1 + 8].copy_from_slice(&2147483647i32.to_le_bytes());
        test_bytes[off1 + 8..off1 + 12].copy_from_slice(&(20000i32).to_le_bytes());
        test_bytes[off1 + 12..off1 + 14].copy_from_slice(&130u16.to_le_bytes());
        test_bytes[off1 + 14] = 64;
        test_bytes[off1 + 15] = 1;
        test_bytes[off1 + 16] = NO_LORE;

        let codebook = StarCodebookView::parse(&test_bytes).expect("codebook should parse");
        assert_eq!(codebook.star_count(), 2);
        assert_eq!(codebook.anomaly_count(), 0);

        let star0 = codebook.get_star(0).expect("star 0 should exist");
        assert_eq!(star0.mag_permyriad, -14600);
        assert_eq!(star0.lode_tier, 0);
        assert_eq!(star0.lore_idx, 0);

        let star1 = codebook.get_star(1).expect("star 1 should exist");
        assert_eq!(star1.mag_permyriad, 20000);
        assert_eq!(star1.lore_idx, NO_LORE);
        assert!((star1.ra_normalized() - 1.0).abs() < 1e-4);
        assert!((star1.dec_normalized() - 1.0).abs() < 1e-4);

        // Nearest centroid test
        let query_5d = [0.99f32, 0.99f32, 0.24f32, 0.5f32, 0.1f32];
        let nearest = codebook.detokenize_embedding(&query_5d).expect("nearest star");
        assert_eq!(nearest.star_idx, 1);
    }
}
