//! Static faction data — 13 canonical factions.

use crate::faction::*;

/// Static array of all 13 faction definitions, indexed by their frozen IDs.
pub const FACTIONS: &[FactionDef] = &[
    FactionDef { id: FactionId::Thornguard, public_name: "The Thornguard", hidden_name: "The Blade That Makes All Debts Equal", primary_economy: "law_enforcement", raid_affinity: RaidAffinity::EqualKnife, world_boss_id: WorldBossId(0), unique_relic_id: RelicId(0), hostile_to: &[], allied_with: &[], can_be_destroyed: false, can_be_reformed: true, can_be_refused: true },
    FactionDef { id: FactionId::Murkveil, public_name: "Murkveil Grave-Water Cell", hidden_name: "The River Beneath the Grave", primary_economy: "black_market_provenance", raid_affinity: RaidAffinity::GraveWater, world_boss_id: WorldBossId(1), unique_relic_id: RelicId(1), hostile_to: &[FactionId::Thornguard, FactionId::LedgerChurch], allied_with: &[], can_be_destroyed: false, can_be_reformed: true, can_be_refused: true },
    FactionDef { id: FactionId::LedgerChurch, public_name: "The Ledger Church", hidden_name: "The Bell Paid Once at the End", primary_economy: "burial_debt_and_absolution", raid_affinity: RaidAffinity::LastToll, world_boss_id: WorldBossId(2), unique_relic_id: RelicId(2), hostile_to: &[FactionId::FreeGraves], allied_with: &[], can_be_destroyed: false, can_be_reformed: true, can_be_refused: true },
    FactionDef { id: FactionId::SenexConvocation, public_name: "The Senex Convocation", hidden_name: "The Hand That Files the Dead", primary_economy: "forced_labor_and_bureaucracy", raid_affinity: RaidAffinity::CleanIndex, world_boss_id: WorldBossId(3), unique_relic_id: RelicId(3), hostile_to: &[FactionId::FreeGraves], allied_with: &[], can_be_destroyed: false, can_be_reformed: true, can_be_refused: true },
    FactionDef { id: FactionId::FreeGraves, public_name: "The Free Graves", hidden_name: "The Hand That Held Mercy Underwater", primary_economy: "unowned_burial_and_refusal", raid_affinity: RaidAffinity::MercyDrowned, world_boss_id: WorldBossId(4), unique_relic_id: RelicId(4), hostile_to: &[FactionId::LedgerChurch, FactionId::SenexConvocation], allied_with: &[], can_be_destroyed: false, can_be_reformed: false, can_be_refused: true },
    FactionDef { id: FactionId::IronmoorCompact, public_name: "Ironmoor Compact", hidden_name: "The Hand That Held Mercy Underwater", primary_economy: "trade_fishing_and_dock_markets", raid_affinity: RaidAffinity::MercyDrowned, world_boss_id: WorldBossId(5), unique_relic_id: RelicId(5), hostile_to: &[], allied_with: &[FactionId::ShatteredReachCorsairs], can_be_destroyed: false, can_be_reformed: true, can_be_refused: true },
    FactionDef { id: FactionId::DuskwealdHuntKin, public_name: "Duskweald Hunt-Kin", hidden_name: "The Injury That Arrives Before the Arrow", primary_economy: "hunting_ecology_and_tracking", raid_affinity: RaidAffinity::FarWound, world_boss_id: WorldBossId(6), unique_relic_id: RelicId(6), hostile_to: &[], allied_with: &[], can_be_destroyed: false, can_be_reformed: true, can_be_refused: true },
    FactionDef { id: FactionId::AshholdLegion, public_name: "Ashhold Legion", hidden_name: "The Blood Owed Before Birth", primary_economy: "war_memory_fire_oaths", raid_affinity: RaidAffinity::RedDebt, world_boss_id: WorldBossId(7), unique_relic_id: RelicId(7), hostile_to: &[FactionId::RimegateClans], allied_with: &[], can_be_destroyed: true, can_be_reformed: true, can_be_refused: true },
    FactionDef { id: FactionId::RimegateClans, public_name: "Rimegate Clans", hidden_name: "The Root That Would Not Kneel", primary_economy: "hospitality_law_survival_hunting", raid_affinity: RaidAffinity::StoneRoot, world_boss_id: WorldBossId(8), unique_relic_id: RelicId(8), hostile_to: &[FactionId::AshholdLegion], allied_with: &[], can_be_destroyed: false, can_be_reformed: true, can_be_refused: true },
    FactionDef { id: FactionId::ShatteredReachCorsairs, public_name: "Shattered Reach Corsairs", hidden_name: "The Star With No Witness Inside", primary_economy: "sea_routes_smuggling_song_tithe", raid_affinity: RaidAffinity::HollowStar, world_boss_id: WorldBossId(9), unique_relic_id: RelicId(9), hostile_to: &[], allied_with: &[FactionId::IronmoorCompact], can_be_destroyed: false, can_be_reformed: true, can_be_refused: true },
    FactionDef { id: FactionId::DreadLatticeNulls, public_name: "Dread Lattice Nulls", hidden_name: "The Two Who Saw Otherwise", primary_economy: "route_erasure_and_map_instability", raid_affinity: RaidAffinity::DoubleWitness, world_boss_id: WorldBossId(10), unique_relic_id: RelicId(10), hostile_to: &[], allied_with: &[], can_be_destroyed: false, can_be_reformed: false, can_be_refused: true },
    FactionDef { id: FactionId::ScornEngineVoidwoken, public_name: "The Voidwoken / Scorn Engine", hidden_name: "The Star With No Witness Inside", primary_economy: "void_property_extraction_and_kernel_prayer", raid_affinity: RaidAffinity::HollowStar, world_boss_id: WorldBossId(11), unique_relic_id: RelicId(11), hostile_to: &[], allied_with: &[], can_be_destroyed: false, can_be_reformed: false, can_be_refused: true },
    FactionDef { id: FactionId::OutsideWheelWeaver, public_name: "Outside the Wheel / Weaver Crown", hidden_name: "The Thirteenth Spoke That Turns Nothing", primary_economy: "ownership_refusal_and_unspawned_consequence", raid_affinity: RaidAffinity::OutsideWheel, world_boss_id: WorldBossId(12), unique_relic_id: RelicId(12), hostile_to: &[], allied_with: &[], can_be_destroyed: false, can_be_reformed: false, can_be_refused: true },
];
