//! Static fae boss data — 13 canonical fae encounters.

use crate::faction::FactionId;
use crate::fae::{FaeBossDef, FaeMoralBand};
use crate::solution_path::SolutionPathKind;

/// The 13 canonical fae boss encounters.
pub const FAE_BOSSES: &[FaeBossDef] = &[
    FaeBossDef { id: "the_walking_milestone", faction_id: FactionId::Thornguard, display_name: "The Walking Milestone", court: "The Milestone Court", fae_type: "road-fae / boundary judge", moral_band: FaeMoralBand::SternGood, zone_bias: &["Thornhaven roads", "Ironmoor causeways", "old border stones"], folklore_hint: "A stone marker changes distance depending on whether the traveler lied that day.", quest_id: "where_the_road_was_promised", solution_paths: &[SolutionPathKind::Diplomacy, SolutionPathKind::Provenance, SolutionPathKind::RouteMastery, SolutionPathKind::Combat, SolutionPathKind::Refusal], reward_id: "milestone_without_a_king" },
    FaeBossDef { id: "the_purse_that_laughed", faction_id: FactionId::Murkveil, display_name: "The Purse That Laughed", court: "The Underleaf Exchange", fae_type: "bargain-fae / gift eater", moral_band: FaeMoralBand::MischievousToEvil, zone_bias: &["Murkveil Depths", "canal markets", "black-market shrines"], folklore_hint: "A purse laughs when a gift is priced.", quest_id: "never_sell_a_gift", solution_paths: &[SolutionPathKind::Stealth, SolutionPathKind::Diplomacy, SolutionPathKind::Trade, SolutionPathKind::Provenance, SolutionPathKind::Combat], reward_id: "unpriced_purse" },
    FaeBossDef { id: "the_baptismal_hag", faction_id: FactionId::LedgerChurch, display_name: "The Baptismal Hag", court: "The Well-Mothers", fae_type: "well-fae / grief midwife", moral_band: FaeMoralBand::GoodToLichGradeDependingOnPollution, zone_bias: &["chapel wells", "Grey Orchard", "burial springs"], folklore_hint: "A well repeats the name of someone who was never baptized.", quest_id: "water_does_not_owe", solution_paths: &[SolutionPathKind::Ritual, SolutionPathKind::Crafting, SolutionPathKind::Diplomacy, SolutionPathKind::Fishing, SolutionPathKind::Combat], reward_id: "debtless_well_cup" },
    FaeBossDef { id: "the_shift_whistle_dryad", faction_id: FactionId::SenexConvocation, display_name: "The Shift-Whistle Dryad", court: "The Root-Tithe Choir", fae_type: "industrialized dryad / labor-bound root spirit", moral_band: FaeMoralBand::TragicEvil, zone_bias: &["Crucible Yards", "Meridian Scar", "worker dormitories"], folklore_hint: "A tree grows iron leaves every time the shift bell rings.", quest_id: "the_tree_that_punched_in", solution_paths: &[SolutionPathKind::Crafting, SolutionPathKind::Diplomacy, SolutionPathKind::Sabotage, SolutionPathKind::Combat, SolutionPathKind::Refusal], reward_id: "rest_whistle" },
    FaeBossDef { id: "the_mourning_briar", faction_id: FactionId::FreeGraves, display_name: "The Mourning Briar", court: "The Moss-Wake", fae_type: "grave-fae / thorn mourner", moral_band: FaeMoralBand::GoodButDangerous, zone_bias: &["Grey Orchard", "Stillborn Crypt", "old battlefield graves"], folklore_hint: "A thorn bush grows flowers only on graves with no owner.", quest_id: "do_not_prune_the_grave", solution_paths: &[SolutionPathKind::Ecology, SolutionPathKind::Ritual, SolutionPathKind::Crafting, SolutionPathKind::Combat, SolutionPathKind::Refusal], reward_id: "thorn_that_refused_the_spade" },
    FaeBossDef { id: "the_pearl_masked_selkie", faction_id: FactionId::IronmoorCompact, display_name: "The Pearl-Masked Selkie", court: "The Brine Masquerade", fae_type: "selkie / tide-bargain fae", moral_band: FaeMoralBand::MischievousToGood, zone_bias: &["Ironmoor Docks", "Shattered Reach", "silver tide pools"], folklore_hint: "A seal asks for its coat back in the voice of a merchant's dead wife.", quest_id: "the_tide_wore_a_face", solution_paths: &[SolutionPathKind::Fishing, SolutionPathKind::Trade, SolutionPathKind::Stealth, SolutionPathKind::Diplomacy, SolutionPathKind::Combat], reward_id: "selkie_coat_button" },
    FaeBossDef { id: "the_hare_with_twelve_shadows", faction_id: FactionId::DuskwealdHuntKin, display_name: "The Hare with Twelve Shadows", court: "The Antlered Unseen", fae_type: "trickster prey-fae / route teacher", moral_band: FaeMoralBand::MischievousGood, zone_bias: &["Duskweald", "Briarhollow", "wrong-road clearings"], folklore_hint: "A hare leaves wolf tracks when chased and child footprints when spared.", quest_id: "the_prey_that_taught_the_hunter", solution_paths: &[SolutionPathKind::Hunting, SolutionPathKind::Ecology, SolutionPathKind::Crafting, SolutionPathKind::RouteMastery, SolutionPathKind::Combat], reward_id: "twelfth_shadow_track" },
    FaeBossDef { id: "the_hearth_that_marched", faction_id: FactionId::AshholdLegion, display_name: "The Hearth That Marched", court: "The Ember-Wives", fae_type: "hearth-fae / war-fire widow", moral_band: FaeMoralBand::TragicGoodToEvil, zone_bias: &["Ashhold", "Cinderfall", "burned villages"], folklore_hint: "A campfire follows a soldier home and waits outside the door.", quest_id: "bring_the_fire_home", solution_paths: &[SolutionPathKind::Ritual, SolutionPathKind::Diplomacy, SolutionPathKind::Crafting, SolutionPathKind::Combat, SolutionPathKind::Refusal], reward_id: "civilian_hearthcoal" },
    FaeBossDef { id: "the_guest_who_was_snow", faction_id: FactionId::RimegateClans, display_name: "The Guest Who Was Snow", court: "The Frost Table", fae_type: "hospitality-fae / winter guest", moral_band: FaeMoralBand::SternGoodToLichGrade, zone_bias: &["Rimegate Peaks", "snow shelters", "clan halls"], folklore_hint: "An extra bowl freezes before anyone sits down.", quest_id: "set_a_place_for_winter", solution_paths: &[SolutionPathKind::Survival, SolutionPathKind::Diplomacy, SolutionPathKind::Crafting, SolutionPathKind::Hunting, SolutionPathKind::Refusal], reward_id: "fourth_bowl_of_snowglass" },
    FaeBossDef { id: "the_siren_who_forgot_hunger", faction_id: FactionId::ShatteredReachCorsairs, display_name: "The Siren Who Forgot Hunger", court: "The Keening Reef", fae_type: "siren-fae / song predator turned oracle", moral_band: FaeMoralBand::MischievousToEvilButRedeemable, zone_bias: &["Shattered Reach", "reef caves", "storm routes"], folklore_hint: "A song lures ships away from rocks, then asks why sailors still fear it.", quest_id: "a_song_is_not_a_net", solution_paths: &[SolutionPathKind::Music, SolutionPathKind::Fishing, SolutionPathKind::Stealth, SolutionPathKind::Diplomacy, SolutionPathKind::Combat], reward_id: "warning_note_conch" },
    FaeBossDef { id: "the_cartwheel_king", faction_id: FactionId::DreadLatticeNulls, display_name: "The Cartwheel King", court: "The Mapless Revel", fae_type: "revel-fae / spatial prankster", moral_band: FaeMoralBand::MischievousToMalevolent, zone_bias: &["Dread Lattice", "wrong-map rooms", "festival ruins"], folklore_hint: "A painted wheel turns on a wall and every door becomes yesterday's door.", quest_id: "do_not_map_the_dance", solution_paths: &[SolutionPathKind::RouteMastery, SolutionPathKind::Crafting, SolutionPathKind::Diplomacy, SolutionPathKind::Refusal, SolutionPathKind::Combat], reward_id: "northless_compass_rose" },
    FaeBossDef { id: "the_moth_that_ate_a_patch", faction_id: FactionId::ScornEngineVoidwoken, display_name: "The Moth That Ate a Patch", court: "The Glass-Moth Procession", fae_type: "glamour-fae / code-eating moth", moral_band: FaeMoralBand::AlienMischievous, zone_bias: &["Scorn Engine", "Void overlays", "broken lantern servers"], folklore_hint: "A moth lands on a terminal and the error message becomes beautiful.", quest_id: "glamour_is_not_code", solution_paths: &[SolutionPathKind::DataMining, SolutionPathKind::Provenance, SolutionPathKind::Crafting, SolutionPathKind::Refusal, SolutionPathKind::Combat], reward_id: "honest_glamour_lantern" },
    FaeBossDef { id: "the_child_who_unwove_crowns", faction_id: FactionId::OutsideWheelWeaver, display_name: "The Child Who Unwove Crowns", court: "The Thirteenth Thimble", fae_type: "secret fae / anti-sovereignty weaver", moral_band: FaeMoralBand::GoodIfRefusedEvilIfOwned, zone_bias: &["unowned roads", "blank graves", "Crown reflections", "places omitted from maps"], folklore_hint: "A child asks for a crown so they can take it apart and make socks for the dead.", quest_id: "the_thimble_that_would_not_rule", solution_paths: &[SolutionPathKind::Crafting, SolutionPathKind::Diplomacy, SolutionPathKind::WitnessBuilding, SolutionPathKind::Refusal, SolutionPathKind::Combat], reward_id: "thirteenth_thimble" },
];
