//! Static world boss data — 13 faction world bosses.

use crate::faction::{FactionId, WorldBossId, RelicId};
use crate::world_boss::FactionWorldBossDef;
use crate::solution_path::SolutionPathKind;

/// The 13 canonical faction world bosses.
pub const WORLD_BOSSES: &[FactionWorldBossDef] = &[
    FactionWorldBossDef { id: WorldBossId(0), faction: FactionId::Thornguard, display_name: "Iron Bailiff Dornsbane", zone_bias: &["Thornhaven", "border courts"], solution_paths: &[SolutionPathKind::Combat, SolutionPathKind::Diplomacy, SolutionPathKind::Provenance, SolutionPathKind::Refusal], true_relic: RelicId(0), echo_relic: Some(RelicId(100)), broken_relic: Some(RelicId(200)) },
    FactionWorldBossDef { id: WorldBossId(1), faction: FactionId::Murkveil, display_name: "The Receipt Eater", zone_bias: &["Murkveil Depths", "canal vaults"], solution_paths: &[SolutionPathKind::Provenance, SolutionPathKind::Stealth, SolutionPathKind::Trade, SolutionPathKind::Combat], true_relic: RelicId(1), echo_relic: Some(RelicId(101)), broken_relic: Some(RelicId(201)) },
    FactionWorldBossDef { id: WorldBossId(2), faction: FactionId::LedgerChurch, display_name: "Saint of Blank Receipts", zone_bias: &["Grey Orchard", "chapel crypts"], solution_paths: &[SolutionPathKind::Ritual, SolutionPathKind::Diplomacy, SolutionPathKind::Provenance, SolutionPathKind::Combat], true_relic: RelicId(2), echo_relic: Some(RelicId(102)), broken_relic: Some(RelicId(202)) },
    FactionWorldBossDef { id: WorldBossId(3), faction: FactionId::SenexConvocation, display_name: "The Foreman of Last Breath", zone_bias: &["Crucible Yards", "Meridian Scar"], solution_paths: &[SolutionPathKind::Sabotage, SolutionPathKind::Crafting, SolutionPathKind::Diplomacy, SolutionPathKind::Combat], true_relic: RelicId(3), echo_relic: Some(RelicId(103)), broken_relic: Some(RelicId(203)) },
    FactionWorldBossDef { id: WorldBossId(4), faction: FactionId::FreeGraves, display_name: "The Grave That Walked Away", zone_bias: &["Stillborn Crypt", "unowned fields"], solution_paths: &[SolutionPathKind::Ritual, SolutionPathKind::Ecology, SolutionPathKind::Refusal, SolutionPathKind::Combat], true_relic: RelicId(4), echo_relic: Some(RelicId(104)), broken_relic: Some(RelicId(204)) },
    FactionWorldBossDef { id: WorldBossId(5), faction: FactionId::IronmoorCompact, display_name: "The Coin Whale", zone_bias: &["Ironmoor Docks", "deep trade lanes"], solution_paths: &[SolutionPathKind::Fishing, SolutionPathKind::Trade, SolutionPathKind::Diplomacy, SolutionPathKind::Combat], true_relic: RelicId(5), echo_relic: Some(RelicId(105)), broken_relic: Some(RelicId(205)) },
    FactionWorldBossDef { id: WorldBossId(6), faction: FactionId::DuskwealdHuntKin, display_name: "The White Hart of Wrong Roads", zone_bias: &["Duskweald", "wrong-road clearings"], solution_paths: &[SolutionPathKind::Hunting, SolutionPathKind::RouteMastery, SolutionPathKind::Ecology, SolutionPathKind::Combat], true_relic: RelicId(6), echo_relic: Some(RelicId(106)), broken_relic: Some(RelicId(206)) },
    FactionWorldBossDef { id: WorldBossId(7), faction: FactionId::AshholdLegion, display_name: "Cinder Standard-Bearer", zone_bias: &["Ashhold", "Cinderfall"], solution_paths: &[SolutionPathKind::Combat, SolutionPathKind::Diplomacy, SolutionPathKind::Ritual, SolutionPathKind::Refusal], true_relic: RelicId(7), echo_relic: Some(RelicId(107)), broken_relic: Some(RelicId(207)) },
    FactionWorldBossDef { id: WorldBossId(8), faction: FactionId::RimegateClans, display_name: "The Glacier Judge", zone_bias: &["Rimegate Peaks", "ice courts"], solution_paths: &[SolutionPathKind::Survival, SolutionPathKind::Diplomacy, SolutionPathKind::Hunting, SolutionPathKind::Combat], true_relic: RelicId(8), echo_relic: Some(RelicId(108)), broken_relic: Some(RelicId(208)) },
    FactionWorldBossDef { id: WorldBossId(9), faction: FactionId::ShatteredReachCorsairs, display_name: "The Anchor That Sang", zone_bias: &["Shattered Reach", "storm routes"], solution_paths: &[SolutionPathKind::Music, SolutionPathKind::Fishing, SolutionPathKind::Stealth, SolutionPathKind::Combat], true_relic: RelicId(9), echo_relic: Some(RelicId(109)), broken_relic: Some(RelicId(209)) },
    FactionWorldBossDef { id: WorldBossId(10), faction: FactionId::DreadLatticeNulls, display_name: "The Null Cartographer", zone_bias: &["Dread Lattice", "erased routes"], solution_paths: &[SolutionPathKind::RouteMastery, SolutionPathKind::DataMining, SolutionPathKind::Provenance, SolutionPathKind::Combat], true_relic: RelicId(10), echo_relic: Some(RelicId(110)), broken_relic: Some(RelicId(210)) },
    FactionWorldBossDef { id: WorldBossId(11), faction: FactionId::ScornEngineVoidwoken, display_name: "The Patch That Prayed", zone_bias: &["Scorn Engine", "kernel shrines"], solution_paths: &[SolutionPathKind::DataMining, SolutionPathKind::Crafting, SolutionPathKind::Refusal, SolutionPathKind::Combat], true_relic: RelicId(11), echo_relic: Some(RelicId(111)), broken_relic: Some(RelicId(211)) },
    FactionWorldBossDef { id: WorldBossId(12), faction: FactionId::OutsideWheelWeaver, display_name: "The Crowned Spawn That Was Not Spawned", zone_bias: &["unspawned zones", "Crown reflections"], solution_paths: &[SolutionPathKind::Refusal, SolutionPathKind::WitnessBuilding, SolutionPathKind::Diplomacy, SolutionPathKind::Combat], true_relic: RelicId(12), echo_relic: None, broken_relic: None },
];
