//! Runs the karaoke word-timing process against the real whisper
//! transcript of `D:\seanm\Documents\Sound Recordings\453am.wav`
//! (`--model base --word_timestamps True`, 2026-08-16).
//!
//! Repeatable, deterministic input: `F:\v3\.forge\reel-out\453am.words.tsv`
//! (`start_ms<TAB>end_ms<TAB>word`, one line per ASR word, extracted
//! verbatim from that whisper run's `segments[].words[]` -- extraction is
//! a one-line PowerShell `ConvertFrom-Json` pass, not hand-typed). This
//! example reads that file rather than hardcoding words in Rust, so
//! re-running it after regenerating the TSV (a new take, a correction)
//! reproduces the exact same deck from the exact same numbers every time
//! -- no re-typing, no drift.
//!
//! Run: `cargo run --example 453am -p forge-reel-v3`

use forge_reel_v3::beats::{compile_beats, RawSegment};
use forge_reel_v3::droplaw::{attention_trit, DropLawCompiler};
use forge_reel_v3::karaoke::KaraokeWord;
use forge_reel_v3::render_karaoke::{render, thirds};

fn main() {
    let tsv_path = "F:\\v3\\.forge\\reel-out\\453am.words.tsv";
    let tsv = std::fs::read_to_string(tsv_path).expect("read words.tsv");

    let words: Vec<KaraokeWord> = tsv
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|line| {
            let mut parts = line.splitn(3, '\t');
            let start_ms: u32 = parts.next().expect("start_ms column").parse().expect("start_ms int");
            let end_ms: u32 = parts.next().expect("end_ms column").parse().expect("end_ms int");
            let word = parts.next().expect("word column").to_string();
            KaraokeWord { word, start_ms, end_ms }
        })
        .collect();

    let sections = thirds(&words);
    // Deadpan Kokoro (bf_lily) narration mixed with a slowed/pitched
    // 1923 reel ("Star of Munster", CC-BY-SA, archive.org) as a bed --
    // generated by this crate's own process, lives on F: like everything
    // else this pipeline writes, never D:.
    let audio_src = "file:///F:/v3/.forge/reel-out/453am-mixed.wav";
    let html = render(&words, &sections, audio_src, "453am");

    let out_dir = "F:\\v3\\.forge\\reel-out";
    std::fs::create_dir_all(out_dir).expect("create .forge/reel-out");
    let out_path = format!("{out_dir}\\453am.html");
    std::fs::write(&out_path, &html).expect("write 453am.html");

    println!(
        "{} words, {} sections -> {out_path} ({} bytes)",
        words.len(),
        sections.len(),
        html.len()
    );
    for s in &sections {
        println!("  [{}] {}-{}ms", s.accent, s.start_ms, s.end_ms);
    }

    // Real attention-criticality receipt: reuse beats::compile_beats (each
    // word treated as its own RawSegment, same merge-under-8s floor) to
    // get Role/Transition/Stakes-bearing Frames, then run the actual
    // droplaw pacing analysis on this real recording's own timing.
    let segments: Vec<RawSegment> = words
        .iter()
        .map(|w| RawSegment { start_ms: w.start_ms, end_ms: w.end_ms, text: w.word.clone() })
        .collect();
    let beats = compile_beats(&segments, 8_000, 24);
    let mut compiler = DropLawCompiler::new(24);
    compiler.frames = beats.into_iter().map(|b| b.frame).collect();
    let analysis = compiler.analyze();
    let trit = attention_trit(&analysis);

    println!(
        "\nattention_trit = {trit:+} ({}) -- {} criticals, {} warnings",
        match trit {
            1 => "Supercritical",
            0 => "Critical",
            _ => "Subcritical",
        },
        analysis.criticals.len(),
        analysis.warnings.len()
    );
    for c in &analysis.criticals {
        println!("  [CRITICAL] {c}");
    }
    for w in &analysis.warnings {
        println!("  [warning]  {w}");
    }
}
