//! Runs the karaoke word-timing process against the real whisper
//! transcript of the Kokoro-synthesized 39s hackathon pitch narration
//! (`--model small --word_timestamps True`, 2026-08-20).
//!
//! Repeatable, deterministic input: `F:\v3\.forge\reel-out\pitch39s.words.tsv`
//! (`start_ms<TAB>end_ms<TAB>word`), generated by
//! `.forge/reel-out/pitch39s_audio.py` -- re-run that script after any
//! prose edit and this example reproduces the exact same deck from the
//! exact same numbers every time.
//!
//! Run: `cargo run --example pitch39s -p forge-reel-v3`

use forge_reel_v3::beats::{compile_beats, RawSegment};
use forge_reel_v3::droplaw::{attention_trit, DropLawCompiler};
use forge_reel_v3::karaoke::KaraokeWord;
use forge_reel_v3::render_karaoke::{render_forced, Section};

fn main() {
    let tsv_path = "F:\\v3\\.forge\\reel-out\\pitch39s.words.tsv";
    let tsv = std::fs::read_to_string(tsv_path).expect("read words.tsv");

    let words: Vec<KaraokeWord> = tsv
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|line| {
            let mut parts = line.splitn(3, '\t');
            let start_ms: u32 = parts.next().expect("start_ms column").parse().expect("start_ms int");
            let end_ms: u32 = parts.next().expect("end_ms column").parse().expect("end_ms int");
            let word = parts.next().expect("word column").to_string();
            KaraokeWord { word, start_ms, end_ms }
        })
        .collect();

    // Hand-aligned sections (not the generic thirds() 60/30/10 split): the
    // ternary thesis line ("negative one, zero plus one...") and everything
    // after it is the resolution, so the green zone starts exactly there,
    // not wherever a blind time-percentage cut happens to land (Sean
    // 2026-08-20: "needs to hit and be green... align them even better").
    let (Some(first), Some(last)) = (words.first(), words.last()) else {
        panic!("no words");
    };
    let negative_idx = words.iter().position(|w| w.word == "negative").expect("find 'negative'");
    let terminal_idx = words.iter().position(|w| w.word == "terminal,").expect("find 'terminal,'");
    let sections = vec![
        Section { start_ms: first.start_ms, end_ms: words[terminal_idx].start_ms, accent: "#1AE0FF" },
        Section { start_ms: words[terminal_idx].start_ms, end_ms: words[negative_idx].start_ms, accent: "#FF3B6E" },
        Section { start_ms: words[negative_idx].start_ms, end_ms: last.end_ms, accent: "#4DFFB0" },
    ];
    // Force the ternary words to land as a deliberate hit -- "one"/"one."
    // are permanently below emphasis_flags' 4-char eligibility floor, and
    // this line is the thesis, not something to leave to the automatic
    // duration heuristic.
    let force_emphasis: Vec<usize> = (negative_idx..=negative_idx + 4).collect();
    // GifCree.gif (real asset, C:\Users\seanm\Desktop\RAMUSPRIME\visual-art)
    // behind the ternary line only -- Sean 2026-08-20 "use cree too... like
    // behind it", after declining to fabricate Cree number-words (this repo's
    // own animal_signs.rs precedent: unreviewed Cree content is a real
    // cultural-review defect, not a style choice -- "nehiyaw-reviewed
    // corrections only"). The real syllabics-rain visual, not invented text.
    let ternary_end_ms = words[negative_idx + 4].end_ms;
    let bg_window = Some((words[negative_idx].start_ms, ternary_end_ms, "GifCree.gif"));

    // Real proof footage (Sean 2026-08-20 "run the terminal videos longer
    // as long as there is movement... timed to what I am saying in regards
    // to the numbers... stretched out longer we have empty space to fill").
    // freezedetect against the real F:\proof3.mp4 found only ~8.2s of
    // actual scrolling motion total (22.6-27.7s, 45.5-46.9s, 50.7-52.4s --
    // everything else in that 57s source is a frozen frame); proof-clip.mp4
    // is those three real-movement windows concatenated back to back, no
    // dead padding, and the <video loop> tag cycles it for as long as the
    // window below stays open. Window covers the full numbers stretch of
    // the narration -- "two runs, same machine" through "not mixed up with
    // anything else" -- not just the "1.14"/"1.17" span.
    let runs_idx = words.iter().position(|w| w.word == "runs,").expect("find 'runs,'");
    let else_idx = words.iter().position(|w| w.word == "else.").expect("find 'else.'");
    let coatings_idx = words.iter().position(|w| w.word == "coatings,").expect("find 'coatings,'");
    // Two more real dead spots, same .proof-inset treatment, filled with
    // real footage (Sean 2026-08-20, rationale: .forge/grind-log/2026-08-20-pitch39s-dead-spots.md).
    // Closing window mixed 4-up, real 13Forge Studio engine footage, Sean
    // 2026-08-20 "WIP Game Rendering and Engine" (rationale: same log).
    let close_start = words[else_idx].end_ms;
    let close_end = last.end_ms;
    let q = (close_end - close_start) / 4;
    const ENGINE_LABEL: &str = "WIP Game Rendering and Engine";
    let video_insets = [
        (words[coatings_idx].end_ms, words[runs_idx].start_ms, "sewfast-clip.mp4", ""),
        (words[runs_idx].start_ms, words[else_idx].end_ms, "proof-clip.mp4", ""),
        (close_start, close_start + q, "shipip-clip.mp4", ENGINE_LABEL),
        (close_start + q, close_start + 2 * q, "promo-clip.mp4", ENGINE_LABEL),
        (close_start + 2 * q, close_start + 3 * q, "starsblink-clip.mp4", ENGINE_LABEL),
        (close_start + 3 * q, close_end, "ss3-clip.mp4", ENGINE_LABEL),
    ];

    // Real background video (Sean 2026-08-20: "E:\v3\RAMUSPRIME\video\
    // book-1000-drop.mp4... z plane glitch opacity and volume 13%"), full
    // runtime, own audio at 13% under the real narration.
    // Sean 2026-08-20: "volume needs to be about 20% lower" -- 0.13 * 0.8.
    let drop_bg = Some(("book-1000-drop.mp4", 0.104f32));

    // Real Walterdale Bridge photo (Sean 2026-08-20, verified this session
    // by direct view -- C:\Users\seanm\Pictures\20170624_104506 (1).jpg,
    // aerial cable-stay construction shot, Edmonton skyline) -- held through
    // "13 years in industrial coatings," (the credential line it backs),
    // then fades for good. "Walterdale bridge picture should be first."
    let open_photo = Some((words[coatings_idx].end_ms, "walterdale-bridge.jpg"));

    // Real credential badges (Sean 2026-08-20: "AMPP NACE NCSO SSPC badges
    // as they are spoken down below in a line" -- real files, not fetched
    // logos: NCSO/NACE/SSPC screenshots he supplied, IUPAT Local 177 badge
    // (resolves "177" -- his real union local), and his own real Alberta
    // Government Journeyman Certificate scan, extracted at native
    // resolution from JMANCERT.pdf's embedded image so it isn't stretched
    // ("can be first" -- his own credential leads the row, before the
    // outside-body certifications). Each badge tracks the word span of
    // the credential it backs.
    let journeyman_idx = words.iter().position(|w| w.word == "Journeyman").expect("find 'Journeyman'");
    let ncso_idx = words.iter().position(|w| w.word == "NCSO,").expect("find 'NCSO,'");
    let sspc_idx = words.iter().position(|w| w.word == "SSPC-CAS").expect("find 'SSPC-CAS'");
    let nace_idx = words.iter().position(|w| w.word == "NACE").expect("find 'NACE'");
    let bridge_idx = words.iter().position(|w| w.word == "Walterdale").expect("find 'Walterdale'");
    let badges: [(u32, u32, &str, &str); 5] = [
        (words[journeyman_idx].start_ms, words[bridge_idx].end_ms, "jman-cert.jpg", "NAIT / Alberta Journeyman"),
        (words[journeyman_idx].start_ms, words[ncso_idx].end_ms, "badge-iupat.png", "IUPAT Local 177"),
        (words[ncso_idx].start_ms, words[sspc_idx].start_ms, "badge-ncso.png", "NCSO"),
        (words[sspc_idx].start_ms, words[sspc_idx].end_ms + 2_000, "badge-sspc.png", "SSPC-CAS / QP1"),
        (words[nace_idx].start_ms, words[bridge_idx].start_ms, "badge-nace.png", "NACE Coating Inspector Level 2"),
    ];

    // Real close (Sean 2026-08-20: "it will be 13forge.com and then my
    // crate page deveraux.dev", then "got 3 crates.io and deveraux.dev and
    // 13forge.com", then the real profile url
    // "https://crates.io/users/deveraux-dev") -- shown only after the real
    // narration ends, textured with the real Onyx crystal PBR color map.
    // Code home first, personal site next, brand name last.
    let end_cards = ["crates.io/users/deveraux-dev", "deveraux.dev", "13forge.com"];

    let audio_src = "file:///F:/v3/.forge/reel-out/pitch39s-narration.wav";
    let html = render_forced(
        &words,
        &sections,
        audio_src,
        "pitch39s",
        &force_emphasis,
        bg_window,
        &video_insets,
        drop_bg,
        open_photo,
        &badges,
        &end_cards,
    );

    let out_dir = "F:\\v3\\.forge\\reel-out";
    std::fs::create_dir_all(out_dir).expect("create .forge/reel-out");
    let out_path = format!("{out_dir}\\pitch39s.html");
    std::fs::write(&out_path, &html).expect("write pitch39s.html");

    println!(
        "{} words, {} sections -> {out_path} ({} bytes)",
        words.len(),
        sections.len(),
        html.len()
    );
    for s in &sections {
        println!("  [{}] {}-{}ms", s.accent, s.start_ms, s.end_ms);
    }

    let segments: Vec<RawSegment> = words
        .iter()
        .map(|w| RawSegment { start_ms: w.start_ms, end_ms: w.end_ms, text: w.word.clone() })
        .collect();
    let beats = compile_beats(&segments, 8_000, 24);
    let mut compiler = DropLawCompiler::new(24);
    compiler.frames = beats.into_iter().map(|b| b.frame).collect();
    let analysis = compiler.analyze();
    let trit = attention_trit(&analysis);

    println!(
        "\nattention_trit = {trit:+} ({}) -- {} criticals, {} warnings",
        match trit {
            1 => "Supercritical",
            0 => "Critical",
            _ => "Subcritical",
        },
        analysis.criticals.len(),
        analysis.warnings.len()
    );
    for c in &analysis.criticals {
        println!("  [CRITICAL] {c}");
    }
    for w in &analysis.warnings {
        println!("  [warning]  {w}");
    }
}
