//! Pipeline-specific voxel chunk generation using integer-only SplitMix64 hashing.
//!
//! This module implements the deterministic engine pipeline's ORIENT phase:
//! generates 32x32x32 VoxelChunks from a zone grid using integer-only
//! SplitMix64 seed derivation and prime sieve classification.
//!
//! **Integer-only constraint**: All math in this module is pure integer arithmetic.
//! No f32/f64 anywhere in the generation path.
//!
//! **Dependency note**: To avoid a cyclic dependency with forge-zones (which
//! optionally depends on prime-sieve-worldgen), this module defines its own
//! lightweight ZoneId/ZoneGrid representations. Conversion from forge-zones
//! types is handled by downstream consumers.

use crate::classify::{VoxelClassifier, PrimeClassificationSieve};
use crate::types::VoxelType;

/// Pipeline chunk edge length (32 voxels per axis).
pub const PIPELINE_CHUNK_SIZE: usize = 32;

/// Total voxels per pipeline chunk (32^3 = 32,768).
pub const PIPELINE_CHUNK_VOLUME: usize =
    PIPELINE_CHUNK_SIZE * PIPELINE_CHUNK_SIZE * PIPELINE_CHUNK_SIZE;

/// Zone identifier for the pipeline — mirrors forge-zones ZoneId as a u8.
///
/// Using a raw u8 avoids circular dependency with forge-zones.
/// Values match forge-zones::zone_grid::ZoneId repr:
///   0=Empty, 1=Prairie, 2=Forest, 3=Wetland, 4=Blackearth,
///   5=Rocky, 6=Boreal, 7=Riparian, 8=Dungeon, 9=Town
pub type PipelineZoneId = u8;

/// Zone ID value representing an empty/unclassified cell.
pub const ZONE_EMPTY: PipelineZoneId = 0;

/// 32x32 zone grid for the pipeline — mirrors forge-zones ZoneGrid layout.
///
/// Each cell holds a PipelineZoneId (u8). Row-major: `cells[row][col]`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PipelineZoneGrid {
    /// 2D grid of zone IDs (32x32).
    pub cells: [[PipelineZoneId; 32]; 32],
}

impl PipelineZoneGrid {
    /// Create an empty grid (all cells = ZONE_EMPTY).
    pub fn empty() -> Self {
        Self {
            cells: [[ZONE_EMPTY; 32]; 32],
        }
    }
}

/// A single voxel cell in the pipeline chunk.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PipelineVoxelCell {
    /// The spiral index used to classify this voxel.
    pub spiral_index: u64,
    /// Classification: Void (prime) or Matter (composite with factor count).
    pub voxel_type: VoxelType,
    /// Local position within the chunk (x, y, z each in 0..32).
    pub local_pos: (u8, u8, u8),
}

/// A 32x32x32 voxel chunk generated by the deterministic pipeline.
///
/// Uses Vec storage since `[[[PipelineVoxelCell; 32]; 32]; 32]` would overflow the stack.
#[derive(Debug, Clone)]
pub struct PipelineVoxelChunk {
    /// All 32,768 voxels in the chunk (row-major: z -> y -> x).
    pub cells: Vec<PipelineVoxelCell>,
    /// The local seed derived for this chunk.
    pub seed: u64,
    /// The zone ID that this chunk belongs to (u8, matches forge-zones ZoneId repr).
    pub zone_id: PipelineZoneId,
    /// Chunk coordinates in world space.
    pub chunk_coords: [i64; 3],
    /// Count of void (prime) voxels.
    pub void_count: u32,
    /// Count of matter (composite) voxels.
    pub matter_count: u32,
}

/// Derive a deterministic local seed from chunk coordinates and master seed.
///
/// Uses SplitMix64-style integer mixing. Zero floating-point operations.
/// Same inputs always produce the same output.
#[inline]
pub fn derive_local_seed(chunk_x: i64, chunk_y: i64, chunk_z: i64, master_seed: u64) -> u64 {
    // Step 1: Combine coordinates via wrapping arithmetic with golden-ratio constants
    let mut hash = master_seed;
    hash = hash.wrapping_add(chunk_x as u64).wrapping_mul(0x9e3779b97f4a7c15);
    hash = hash.wrapping_add(chunk_y as u64).wrapping_mul(0xbf58476d1ce4e5b9);
    hash = hash.wrapping_add(chunk_z as u64).wrapping_mul(0x94d049bb133111eb);

    // Step 2: SplitMix64 finalizer
    hash ^= hash >> 30;
    hash = hash.wrapping_mul(0xbf58476d1ce4e5b9);
    hash ^= hash >> 27;
    hash = hash.wrapping_mul(0x94d049bb133111eb);
    hash ^= hash >> 31;

    hash
}

/// Generate a single pipeline VoxelChunk for a given zone at specified coordinates.
///
/// Algorithm:
/// 1. Derive local seed from chunk coordinates + master seed (SplitMix64)
/// 2. Compute sieve upper bound from local seed
/// 3. For each of 32^3 voxel positions:
///    a. Compute spiral index from local seed + linear position offset
///    b. Classify via prime sieve: prime -> Void, composite -> Matter
/// 4. Return the populated chunk with void/matter counts
///
/// Integer-only: no f32/f64 in this function.
pub fn generate_pipeline_chunk(
    zone: PipelineZoneId,
    chunk_coords: [i64; 3],
    master_seed: u64,
) -> PipelineVoxelChunk {
    let local_seed = derive_local_seed(
        chunk_coords[0],
        chunk_coords[1],
        chunk_coords[2],
        master_seed,
    );

    // Sieve upper bound: enough to cover all 32^3 voxels plus seed offset.
    // Minimum 65536 to ensure coverage; scale with seed for variety.
    let sieve_upper_bound = 65_536u64 + (local_seed % 65_536);
    let sieve = PrimeClassificationSieve::new(sieve_upper_bound);
    let classifier = VoxelClassifier::new(sieve);

    // Base index derived from local seed, bounded to sieve range
    let base_index = local_seed % classifier.sieve().upper_bound;

    let mut cells = Vec::with_capacity(PIPELINE_CHUNK_VOLUME);
    let mut void_count: u32 = 0;
    let mut matter_count: u32 = 0;

    for lz in 0..PIPELINE_CHUNK_SIZE as u8 {
        for ly in 0..PIPELINE_CHUNK_SIZE as u8 {
            for lx in 0..PIPELINE_CHUNK_SIZE as u8 {
                // Linear offset within the chunk
                let local_linear = (lz as u64) * 1024 + (ly as u64) * 32 + (lx as u64);
                // Spiral index wraps within sieve bounds
                let spiral_index =
                    base_index.wrapping_add(local_linear) % classifier.sieve().upper_bound;

                let voxel_type = classifier.classify(spiral_index);

                match voxel_type {
                    VoxelType::Void => void_count += 1,
                    VoxelType::Matter { .. } => matter_count += 1,
                }

                cells.push(PipelineVoxelCell {
                    spiral_index,
                    voxel_type,
                    local_pos: (lx, ly, lz),
                });
            }
        }
    }

    PipelineVoxelChunk {
        cells,
        seed: local_seed,
        zone_id: zone,
        chunk_coords,
        void_count,
        matter_count,
    }
}

/// Generate all pipeline VoxelChunks for a PipelineZoneGrid.
///
/// Iterates the 32x32 grid. For each non-Empty cell (zone_id != 0),
/// generates a PipelineVoxelChunk at coordinates (col, 0, row).
///
/// Integer-only: no f32/f64 in this function.
pub fn generate_world(grid: &PipelineZoneGrid, master_seed: u64) -> Vec<PipelineVoxelChunk> {
    let mut chunks = Vec::new();

    for row in 0..32_usize {
        for col in 0..32_usize {
            let zone_id = grid.cells[row][col];
            if zone_id == ZONE_EMPTY {
                continue;
            }
            let chunk_coords = [col as i64, 0_i64, row as i64];
            let chunk = generate_pipeline_chunk(zone_id, chunk_coords, master_seed);
            chunks.push(chunk);
        }
    }

    chunks
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_derive_local_seed_deterministic() {
        let a = derive_local_seed(1, 2, 3, 42);
        let b = derive_local_seed(1, 2, 3, 42);
        assert_eq!(a, b);
    }

    #[test]
    fn test_derive_local_seed_different_coords() {
        let a = derive_local_seed(0, 0, 0, 42);
        let b = derive_local_seed(1, 0, 0, 42);
        assert_ne!(a, b);
    }

    #[test]
    fn test_derive_local_seed_different_seeds() {
        let a = derive_local_seed(5, 5, 5, 100);
        let b = derive_local_seed(5, 5, 5, 200);
        assert_ne!(a, b);
    }

    #[test]
    fn test_generate_pipeline_chunk_volume() {
        let chunk = generate_pipeline_chunk(2, [0, 0, 0], 42); // 2 = Forest
        assert_eq!(chunk.cells.len(), PIPELINE_CHUNK_VOLUME);
        assert_eq!(
            chunk.void_count + chunk.matter_count,
            PIPELINE_CHUNK_VOLUME as u32
        );
    }

    #[test]
    fn test_generate_pipeline_chunk_determinism() {
        let c1 = generate_pipeline_chunk(1, [3, -1, 7], 999); // 1 = Prairie
        let c2 = generate_pipeline_chunk(1, [3, -1, 7], 999);
        assert_eq!(c1.seed, c2.seed);
        assert_eq!(c1.void_count, c2.void_count);
        assert_eq!(c1.matter_count, c2.matter_count);
        assert_eq!(c1.cells.len(), c2.cells.len());
        for (a, b) in c1.cells.iter().zip(c2.cells.iter()) {
            assert_eq!(a.spiral_index, b.spiral_index);
            assert_eq!(a.voxel_type, b.voxel_type);
        }
    }

    #[test]
    fn test_generate_pipeline_chunk_metadata() {
        let chunk = generate_pipeline_chunk(8, [10, 20, 30], 12345); // 8 = Dungeon
        assert_eq!(chunk.zone_id, 8);
        assert_eq!(chunk.chunk_coords, [10, 20, 30]);
        assert_ne!(chunk.seed, 0);
    }

    #[test]
    fn test_generate_world_skips_empty() {
        let grid = PipelineZoneGrid::empty();
        let chunks = generate_world(&grid, 42);
        assert_eq!(chunks.len(), 0);
    }

    #[test]
    fn test_generate_world_generates_non_empty() {
        let mut grid = PipelineZoneGrid::empty();
        grid.cells[0][0] = 2; // Forest
        grid.cells[1][2] = 5; // Rocky
        grid.cells[31][31] = 9; // Town

        let chunks = generate_world(&grid, 42);
        assert_eq!(chunks.len(), 3);

        // Verify coordinates match grid positions (col, 0, row)
        assert_eq!(chunks[0].chunk_coords, [0, 0, 0]);
        assert_eq!(chunks[0].zone_id, 2);

        assert_eq!(chunks[1].chunk_coords, [2, 0, 1]);
        assert_eq!(chunks[1].zone_id, 5);

        assert_eq!(chunks[2].chunk_coords, [31, 0, 31]);
        assert_eq!(chunks[2].zone_id, 9);
    }
}
