//! ARCH-017 drift ledger — the Machine side of the Latent-Space Collider.
//!
//! `cargo xtask triage-lateral` audits every `.agents/skills/*/SKILL.md` reference
//! against the tree and rewrites the generated block below. Level-0 FATAL findings
//! never land here (the xtask exits non-zero on the spot); Level-1 WARN rows accrue
//! until the skill is patched, and the escalation test turns the board RED when a
//! skill crosses [`ESCALATION_CAP`] — the compile-time teeth of ARCH-017 §4.

/// Unpatched Level-1 WARNs one skill may accrue before escalation to FATAL.
pub const ESCALATION_CAP: usize = 8;

/// (skill, referent, level) drift rows. Level: 1 = WARN, 2 = SYNC.
// <triage-lateral> generated by `cargo xtask triage-lateral` — do not hand-edit
pub const DRIFT_LEDGER: &[(&str, &str, u8)] = &[
];
// </triage-lateral>

/// Unpatched Level-1 WARN rows carried by `skill`.
pub fn warn_count(skill: &str) -> usize {
    DRIFT_LEDGER.iter().filter(|(s, _, lvl)| *s == skill && *lvl == 1).count()
}

#[cfg(test)]
mod tests {
    use super::*;

    // [BOARD: ARCH-017-TRIAGE]
    #[test]
    fn no_skill_crosses_the_escalation_cap() {
        let mut skills: Vec<&str> = DRIFT_LEDGER.iter().map(|(s, _, _)| *s).collect();
        skills.sort_unstable();
        skills.dedup();
        for skill in skills {
            let n = warn_count(skill);
            assert!(
                n < ESCALATION_CAP,
                "ARCH-017 escalation: skill '{skill}' carries {n} unpatched WARNs (cap {ESCALATION_CAP})"
            );
        }
    }
}
